# é¡¹ç›®ä¿¡æ¯
site_name: Emeric53
site_author: Emeric53
site_description: 
  Welcome to Emeric53's nullspace.
# ä»£ç ä»“åº“ä¿¡æ¯
repo_name: Emeric53/Emeric53.github.io # ä»“åº“åç§°
repo_url: https://github.com/Emeric53/Emeric53.github.io/ # ä»“åº“åœ°å€

# ç‰ˆæƒä¿¡æ¯
copyright: Copyright &copy; 2024 ~ now | ğŸ¦© Emeric Liang

nav:
  - Home: index.md
  - Academic:
      - Computer Science:
          - Coding: "Computer Science/Coding.md"
      - Math:
          - Math Notes: "Math/Math.md"
  - Share:  # å‡è®¾ Share ä½ æ˜¯å…¬å¼€å±•ç¤ºçš„
      - Something: "Share/example.md"

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: light green
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: blue grey
      accent: lime

# # Plugins
# plugins:
#   - tags
#   - blog