[workspace]
name = "emeric53-github-io"
version = "0.1.0"
description = "Emeric53's personal website"
authors = ["Emeric53"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "win-64"]

[dependencies]
python = "3.10.*"

[tasks]
deploy = "mkdocs gh-deploy --force"
start = "mkdocs serve"
build = "mkdocs build"

[pypi-dependencies]
mkdocs-material = ">=9.7.1, <10"
mkdocs-awesome-pages-plugin = ">=2.10.1, <3"
pillow = ">=12.0.0, <13"
cairosvg = ">=2.8.2, <3"
mkdocs-git-revision-date-localized-plugin = ">=1.2.6, <2"
mkdocs-glightbox = ">=0.4.0, <1"
mkdocs-rss-plugin = ">=1.12.0, <2"
mkdocs-minify-plugin = ">=0.8.0, <1"
